# Generated by Django 5.0.6 on 2024-06-30 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('incomplete', 'Incomplete'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='incomplete', max_length=20),
        ),
    ]
